// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	core "github.com/pchchv/bpdf/core"
	entity "github.com/pchchv/bpdf/core/entity"

	mock "github.com/stretchr/testify/mock"

	node "github.com/pchchv/bpdf/node"
)

// BPDF is an autogenerated mock type for the BPDF type
type BPDF struct {
	mock.Mock
}

type BPDF_Expecter struct {
	mock *mock.Mock
}

func (_m *BPDF) EXPECT() *BPDF_Expecter {
	return &BPDF_Expecter{mock: &_m.Mock}
}

// AddAutoRow provides a mock function with given fields: cols
func (_m *BPDF) AddAutoRow(cols ...core.Col) core.Row {
	_va := make([]interface{}, len(cols))
	for _i := range cols {
		_va[_i] = cols[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddAutoRow")
	}

	var r0 core.Row
	if rf, ok := ret.Get(0).(func(...core.Col) core.Row); ok {
		r0 = rf(cols...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Row)
		}
	}

	return r0
}

// BPDF_AddAutoRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAutoRow'
type BPDF_AddAutoRow_Call struct {
	*mock.Call
}

// AddAutoRow is a helper method to define mock.On call
//   - cols ...core.Col
func (_e *BPDF_Expecter) AddAutoRow(cols ...interface{}) *BPDF_AddAutoRow_Call {
	return &BPDF_AddAutoRow_Call{Call: _e.mock.On("AddAutoRow",
		append([]interface{}{}, cols...)...)}
}

func (_c *BPDF_AddAutoRow_Call) Run(run func(cols ...core.Col)) *BPDF_AddAutoRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Col, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Col)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *BPDF_AddAutoRow_Call) Return(_a0 core.Row) *BPDF_AddAutoRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPDF_AddAutoRow_Call) RunAndReturn(run func(...core.Col) core.Row) *BPDF_AddAutoRow_Call {
	_c.Call.Return(run)
	return _c
}

// AddPages provides a mock function with given fields: pages
func (_m *BPDF) AddPages(pages ...core.Page) {
	_va := make([]interface{}, len(pages))
	for _i := range pages {
		_va[_i] = pages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// BPDF_AddPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPages'
type BPDF_AddPages_Call struct {
	*mock.Call
}

// AddPages is a helper method to define mock.On call
//   - pages ...core.Page
func (_e *BPDF_Expecter) AddPages(pages ...interface{}) *BPDF_AddPages_Call {
	return &BPDF_AddPages_Call{Call: _e.mock.On("AddPages",
		append([]interface{}{}, pages...)...)}
}

func (_c *BPDF_AddPages_Call) Run(run func(pages ...core.Page)) *BPDF_AddPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Page, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Page)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *BPDF_AddPages_Call) Return() *BPDF_AddPages_Call {
	_c.Call.Return()
	return _c
}

func (_c *BPDF_AddPages_Call) RunAndReturn(run func(...core.Page)) *BPDF_AddPages_Call {
	_c.Call.Return(run)
	return _c
}

// AddRow provides a mock function with given fields: rowHeight, cols
func (_m *BPDF) AddRow(rowHeight float64, cols ...core.Col) core.Row {
	_va := make([]interface{}, len(cols))
	for _i := range cols {
		_va[_i] = cols[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, rowHeight)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddRow")
	}

	var r0 core.Row
	if rf, ok := ret.Get(0).(func(float64, ...core.Col) core.Row); ok {
		r0 = rf(rowHeight, cols...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Row)
		}
	}

	return r0
}

// BPDF_AddRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRow'
type BPDF_AddRow_Call struct {
	*mock.Call
}

// AddRow is a helper method to define mock.On call
//   - rowHeight float64
//   - cols ...core.Col
func (_e *BPDF_Expecter) AddRow(rowHeight interface{}, cols ...interface{}) *BPDF_AddRow_Call {
	return &BPDF_AddRow_Call{Call: _e.mock.On("AddRow",
		append([]interface{}{rowHeight}, cols...)...)}
}

func (_c *BPDF_AddRow_Call) Run(run func(rowHeight float64, cols ...core.Col)) *BPDF_AddRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Col, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(core.Col)
			}
		}
		run(args[0].(float64), variadicArgs...)
	})
	return _c
}

func (_c *BPDF_AddRow_Call) Return(_a0 core.Row) *BPDF_AddRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPDF_AddRow_Call) RunAndReturn(run func(float64, ...core.Col) core.Row) *BPDF_AddRow_Call {
	_c.Call.Return(run)
	return _c
}

// AddRows provides a mock function with given fields: rows
func (_m *BPDF) AddRows(rows ...core.Row) {
	_va := make([]interface{}, len(rows))
	for _i := range rows {
		_va[_i] = rows[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// BPDF_AddRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRows'
type BPDF_AddRows_Call struct {
	*mock.Call
}

// AddRows is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *BPDF_Expecter) AddRows(rows ...interface{}) *BPDF_AddRows_Call {
	return &BPDF_AddRows_Call{Call: _e.mock.On("AddRows",
		append([]interface{}{}, rows...)...)}
}

func (_c *BPDF_AddRows_Call) Run(run func(rows ...core.Row)) *BPDF_AddRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Row, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Row)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *BPDF_AddRows_Call) Return() *BPDF_AddRows_Call {
	_c.Call.Return()
	return _c
}

func (_c *BPDF_AddRows_Call) RunAndReturn(run func(...core.Row)) *BPDF_AddRows_Call {
	_c.Call.Return(run)
	return _c
}

// FitlnCurrentPage provides a mock function with given fields: heightNewLine
func (_m *BPDF) FitlnCurrentPage(heightNewLine float64) bool {
	ret := _m.Called(heightNewLine)

	if len(ret) == 0 {
		panic("no return value specified for FitlnCurrentPage")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64) bool); ok {
		r0 = rf(heightNewLine)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// BPDF_FitlnCurrentPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FitlnCurrentPage'
type BPDF_FitlnCurrentPage_Call struct {
	*mock.Call
}

// FitlnCurrentPage is a helper method to define mock.On call
//   - heightNewLine float64
func (_e *BPDF_Expecter) FitlnCurrentPage(heightNewLine interface{}) *BPDF_FitlnCurrentPage_Call {
	return &BPDF_FitlnCurrentPage_Call{Call: _e.mock.On("FitlnCurrentPage", heightNewLine)}
}

func (_c *BPDF_FitlnCurrentPage_Call) Run(run func(heightNewLine float64)) *BPDF_FitlnCurrentPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *BPDF_FitlnCurrentPage_Call) Return(_a0 bool) *BPDF_FitlnCurrentPage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPDF_FitlnCurrentPage_Call) RunAndReturn(run func(float64) bool) *BPDF_FitlnCurrentPage_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function with given fields:
func (_m *BPDF) Generate() (core.Document, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 core.Document
	var r1 error
	if rf, ok := ret.Get(0).(func() (core.Document, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() core.Document); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Document)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BPDF_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type BPDF_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *BPDF_Expecter) Generate() *BPDF_Generate_Call {
	return &BPDF_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *BPDF_Generate_Call) Run(run func()) *BPDF_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BPDF_Generate_Call) Return(_a0 core.Document, _a1 error) *BPDF_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BPDF_Generate_Call) RunAndReturn(run func() (core.Document, error)) *BPDF_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentConfig provides a mock function with given fields:
func (_m *BPDF) GetCurrentConfig() *entity.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentConfig")
	}

	var r0 *entity.Config
	if rf, ok := ret.Get(0).(func() *entity.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Config)
		}
	}

	return r0
}

// BPDF_GetCurrentConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentConfig'
type BPDF_GetCurrentConfig_Call struct {
	*mock.Call
}

// GetCurrentConfig is a helper method to define mock.On call
func (_e *BPDF_Expecter) GetCurrentConfig() *BPDF_GetCurrentConfig_Call {
	return &BPDF_GetCurrentConfig_Call{Call: _e.mock.On("GetCurrentConfig")}
}

func (_c *BPDF_GetCurrentConfig_Call) Run(run func()) *BPDF_GetCurrentConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BPDF_GetCurrentConfig_Call) Return(_a0 *entity.Config) *BPDF_GetCurrentConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPDF_GetCurrentConfig_Call) RunAndReturn(run func() *entity.Config) *BPDF_GetCurrentConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetStructure provides a mock function with given fields:
func (_m *BPDF) GetStructure() *node.Node[core.Structure] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStructure")
	}

	var r0 *node.Node[core.Structure]
	if rf, ok := ret.Get(0).(func() *node.Node[core.Structure]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node[core.Structure])
		}
	}

	return r0
}

// BPDF_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type BPDF_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *BPDF_Expecter) GetStructure() *BPDF_GetStructure_Call {
	return &BPDF_GetStructure_Call{Call: _e.mock.On("GetStructure")}
}

func (_c *BPDF_GetStructure_Call) Run(run func()) *BPDF_GetStructure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BPDF_GetStructure_Call) Return(_a0 *node.Node[core.Structure]) *BPDF_GetStructure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPDF_GetStructure_Call) RunAndReturn(run func() *node.Node[core.Structure]) *BPDF_GetStructure_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFooter provides a mock function with given fields: rows
func (_m *BPDF) RegisterFooter(rows ...core.Row) error {
	_va := make([]interface{}, len(rows))
	for _i := range rows {
		_va[_i] = rows[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterFooter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...core.Row) error); ok {
		r0 = rf(rows...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BPDF_RegisterFooter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFooter'
type BPDF_RegisterFooter_Call struct {
	*mock.Call
}

// RegisterFooter is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *BPDF_Expecter) RegisterFooter(rows ...interface{}) *BPDF_RegisterFooter_Call {
	return &BPDF_RegisterFooter_Call{Call: _e.mock.On("RegisterFooter",
		append([]interface{}{}, rows...)...)}
}

func (_c *BPDF_RegisterFooter_Call) Run(run func(rows ...core.Row)) *BPDF_RegisterFooter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Row, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Row)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *BPDF_RegisterFooter_Call) Return(_a0 error) *BPDF_RegisterFooter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPDF_RegisterFooter_Call) RunAndReturn(run func(...core.Row) error) *BPDF_RegisterFooter_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterHeader provides a mock function with given fields: rows
func (_m *BPDF) RegisterHeader(rows ...core.Row) error {
	_va := make([]interface{}, len(rows))
	for _i := range rows {
		_va[_i] = rows[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...core.Row) error); ok {
		r0 = rf(rows...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BPDF_RegisterHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHeader'
type BPDF_RegisterHeader_Call struct {
	*mock.Call
}

// RegisterHeader is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *BPDF_Expecter) RegisterHeader(rows ...interface{}) *BPDF_RegisterHeader_Call {
	return &BPDF_RegisterHeader_Call{Call: _e.mock.On("RegisterHeader",
		append([]interface{}{}, rows...)...)}
}

func (_c *BPDF_RegisterHeader_Call) Run(run func(rows ...core.Row)) *BPDF_RegisterHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.Row, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(core.Row)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *BPDF_RegisterHeader_Call) Return(_a0 error) *BPDF_RegisterHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPDF_RegisterHeader_Call) RunAndReturn(run func(...core.Row) error) *BPDF_RegisterHeader_Call {
	_c.Call.Return(run)
	return _c
}

// NewBPDF creates a new instance of BPDF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBPDF(t interface {
	mock.TestingT
	Cleanup(func())
}) *BPDF {
	mock := &BPDF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
